import type { StoreApplicationList } from "@/types/domain/store";

export const storeApplicationListMock: StoreApplicationList = {
  content: [
    {
      registrationId: "1",
      accountId: "1",
      name: "매장1",
      ceoName: "대표자명",
      address: "서울특별시 강남구 역삼동",
      landline: "010-1234-5678",
      license: "123-12-12345",
      image: "https://via.placeholder.com/150",
      status: "APPLY",
      reason: "사엽자 정보를 조회할 수 없습니다.",
      createdAt: "2021-01-01",
      updatedAt: "2021-01-01",
    },
    {
      registrationId: "2",
      accountId: "1",
      name: "매장2",
      ceoName: "대표자명",
      address: "서울특별시 강남구 역삼동",
      landline: "010-1234-5678",
      license: "123-12-12345",
      image: "https://via.placeholder.com/150",
      status: "APPROVE",
      reason: "",
      createdAt: "2021-01-01",
      updatedAt: "2021-01-01",
    },
  ],
  page: 1,
  size: 10,
  pageSkipSize: 10,
  count: 100,
  fastForwardPage: 10,
  fastBackwardPage: 1,
  isFirst: true,
  isLast: false,
};
